server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_mysql?serverTimezone=CST
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: MM/dd/YYYY HH:mm:ss
    time-zone: GMT+8

    mvc:
      view:
        suffix: .html
      static-path-pattern: /**
      resources:
        static-locations: classpath:/static/
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml